# Generated by Django 6.0.5 on 2026-09-16 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0026_feature_whitelist_personal_training'),
        ('members', '0016_member_address'),
        ('plans', '0011_alter_membershipplan_duration_days'),
        ('subscriptions', '0019_taskrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, help_text='Costo mensual del entrenamiento personal. Se factura como SubscriptionItem.', max_digits=10, verbose_name='Precio mensual')),
                ('billing_mode', models.CharField(choices=[('monthly', 'Mensual'), ('sessions', 'Por sesiones')], default='monthly', help_text='Mensual: cuota mensual fija. Por sesiones: el staff asigna al socio en modalidad mensual o en un paquete de N sesiones.', max_length=20, verbose_name='Modalidad de cobro')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración de la sesión (minutos)')),
                ('trainer_gender', models.CharField(choices=[('male', 'Varón'), ('female', 'Mujer'), ('any', 'Varón o mujer')], default='any', help_text='Restringe qué trainers pueden asignarse a esta oferta.', max_length=10, verbose_name='Género del entrenador/a')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_training_services', to='gyms.gym', verbose_name='Gimnasio')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_training_services', to='plans.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Oferta de entrenamiento personal',
                'verbose_name_plural': 'Ofertas de entrenamiento personal',
                'ordering': ['name'],
                'unique_together': {('gym', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PersonalTrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=20, verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('modality', models.CharField(choices=[('monthly', 'Mensual'), ('package', 'Paquete de sesiones')], default='monthly', help_text='Mensual: se factura la cuota del servicio. Paquete: el socio asiste a un número fijo de sesiones.', max_length=20, verbose_name='Modalidad')),
                ('package_total_sessions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de sesiones del paquete')),
                ('session_price', models.DecimalField(blank=True, decimal_places=2, help_text='Costo por sesión para este socio.', max_digits=10, null=True, verbose_name='Precio por sesión')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Cuánto pagó el socio de este paquete de sesiones.', max_digits=10, verbose_name='Monto cobrado')),
                ('sellado_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto opcional de sellado o coseguro que cobra el gimnasio.', max_digits=10, null=True, verbose_name='Sellado / coseguro')),
                ('sellado_paid', models.BooleanField(default=False, verbose_name='Sellado cobrado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_training_assignments', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_training_assignments', to='members.member', verbose_name='Miembro')),
                ('subscription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_training_assignments', to='subscriptions.subscriptionitem', verbose_name='Item de suscripción')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_training_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador/a')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='personal_training.personaltrainingservice', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Asignación de entrenamiento personal',
                'verbose_name_plural': 'Asignaciones de entrenamiento personal',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTrainingSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha de la sesión')),
                ('source', models.CharField(choices=[('auto', 'Automática'), ('manual', 'Manual')], default='manual', help_text='Manual (staff) o automática.', max_length=20, verbose_name='Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='personal_training.personaltrainingassignment', verbose_name='Asignación')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_training_session_records', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_training_session_records', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento personal',
                'verbose_name_plural': 'Sesiones de entrenamiento personal',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTrainingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=20, verbose_name='Día solicitado')),
                ('requested_start_time', models.TimeField(verbose_name='Hora inicio solicitada')),
                ('requested_end_time', models.TimeField(verbose_name='Hora fin solicitada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('executed', 'Ejecutado'), ('rejected', 'Rechazado'), ('cancelled_by_member', 'Cancelado por el socio'), ('cancelled_by_staff', 'Cancelado por el staff')], default='pending', max_length=20, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='personal_training.personaltrainingassignment', verbose_name='Asignación')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_training_change_requests', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_training_change_requests', to='members.member', verbose_name='Miembro')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de entrenamiento personal',
                'verbose_name_plural': 'Solicitudes de cambio de entrenamiento personal',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['gym', 'status'], name='personal_tr_gym_id_0b1b71_idx'), models.Index(fields=['member', 'status'], name='personal_tr_member__81eff0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('member', 'assignment'), name='unique_pending_pt_change_request')],
            },
        ),
        migrations.AddConstraint(
            model_name='personaltrainingassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='personal_training_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='personaltrainingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('gym', 'member', 'day', 'start_time'), name='unique_active_pt_assignment'),
        ),
        migrations.AddConstraint(
            model_name='personaltrainingsessionrecord',
            constraint=models.UniqueConstraint(fields=('assignment', 'date'), name='unique_pt_session_record'),
        ),
    ]
