# Generated by Django 6.0.5 on 2026-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainingassignment',
            name='no_show_scan_until',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual ya se evaluaron las no asistencias de este paquete.', null=True, verbose_name='Descuento de no asistencia procesado hasta'),
        ),
        migrations.AlterField(
            model_name='personaltrainingsessionrecord',
            name='source',
            field=models.CharField(choices=[('auto', 'Automática'), ('manual', 'Manual'), ('no_show', 'No asistió')], default='manual', help_text='Manual (staff) o automática.', max_length=20, verbose_name='Origen'),
        ),
    ]
