# Generated by Django 6.0.5 on 2026-09-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0030_feature_whitelist_outings'),
        ('members', '0017_member_whatsapp'),
        ('plans', '0011_alter_membershipplan_duration_days'),
        ('subscriptions', '0020_subscriptionitem_personal_training_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('meeting_place', models.CharField(blank=True, help_text='Lugar donde arranca la salida.', max_length=200, verbose_name='Punto de encuentro')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, help_text='Costo mensual de la salida. Se factura como SubscriptionItem.', max_digits=10, verbose_name='Precio mensual')),
                ('billing_mode', models.CharField(choices=[('monthly', 'Mensual'), ('sessions', 'Por sesiones')], default='monthly', help_text='Mensual: cuota mensual fija. Por sesiones: el staff inscribe a cada socio en modalidad mensual o en un paquete de N sesiones.', max_length=20, verbose_name='Modalidad de cobro')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outings', to='gyms.gym', verbose_name='Gimnasio')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outings', to='plans.service', verbose_name='Servicio')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outings', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador/a')),
            ],
            options={
                'verbose_name': 'Salida grupal',
                'verbose_name_plural': 'Salidas grupales',
                'ordering': ['name'],
                'unique_together': {('gym', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OutingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=20, verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('outing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='outings.outing', verbose_name='Salida')),
            ],
            options={
                'verbose_name': 'Horario de salida',
                'verbose_name_plural': 'Horarios de salidas',
            },
        ),
        migrations.CreateModel(
            name='OutingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('monthly', 'Mensual'), ('package', 'Paquete de sesiones')], default='monthly', help_text='Mensual: se factura la cuota de la salida. Paquete: el socio asiste a un número fijo de sesiones.', max_length=20, verbose_name='Modalidad')),
                ('package_total_sessions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de sesiones del paquete')),
                ('session_price', models.DecimalField(blank=True, decimal_places=2, help_text='Costo por salida para este socio.', max_digits=10, null=True, verbose_name='Precio por sesión')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Cuánto pagó el socio de este paquete de sesiones.', max_digits=10, verbose_name='Monto cobrado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscripto')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_enrollments', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_enrollments', to='members.member', verbose_name='Miembro')),
                ('subscription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outing_enrollments', to='subscriptions.subscriptionitem', verbose_name='Item de suscripción')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='outings.outingschedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Inscripción a salida',
                'verbose_name_plural': 'Inscripciones a salidas',
            },
        ),
        migrations.CreateModel(
            name='OutingSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha de la sesión')),
                ('source', models.CharField(choices=[('auto', 'Automática'), ('manual', 'Manual')], default='manual', help_text='Automática (check-in) o manual (staff).', max_length=20, verbose_name='Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='outings.outingenrollment', verbose_name='Inscripción')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_session_records', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_session_records', to='members.member', verbose_name='Miembro')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_records', to='outings.outingschedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Sesión asistida',
                'verbose_name_plural': 'Sesiones asistidas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='outingschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='outingschedule_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='outingschedule',
            unique_together={('outing', 'day', 'start_time')},
        ),
        migrations.AddConstraint(
            model_name='outingenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('gym', 'member', 'schedule'), name='unique_active_outing_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='outingsessionrecord',
            constraint=models.UniqueConstraint(fields=('enrollment', 'date', 'schedule'), name='unique_outing_session_record'),
        ),
    ]
