# Generated by Django 6.0.5 on 2026-09-22 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0030_feature_whitelist_outings'),
        ('members', '0017_member_whatsapp'),
        ('outings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutingEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('enroll', 'Inscripción'), ('unenroll', 'Baja')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled_by_member', 'Cancelado por el socio'), ('cancelled_by_staff', 'Cancelado por el staff')], default='pending', max_length=20, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_requests', to='outings.outingenrollment', verbose_name='Inscripción')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_enrollment_requests', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_enrollment_requests', to='members.member', verbose_name='Miembro')),
                ('outing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_requests', to='outings.outing', verbose_name='Salida')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_requests', to='outings.outingschedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Solicitud de salida grupal',
                'verbose_name_plural': 'Solicitudes de salidas grupales',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['gym', 'status'], name='outings_out_gym_id_84ac1b_idx'), models.Index(fields=['member', 'status'], name='outings_out_member__7542f1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('member', 'request_type'), name='unique_pending_outing_enrollment_request')],
            },
        ),
    ]
