# Generated by Django 6.0.5 on 2026-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0002_outingenrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='route_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se calcula automáticamente desde el recorrido (fórmula haversine).', max_digits=5, null=True, verbose_name='Distancia del recorrido (km)'),
        ),
        migrations.AddField(
            model_name='outing',
            name='route_polyline',
            field=models.JSONField(blank=True, help_text='Puntos del recorrido como [[lat, lng], ...] en orden. Se dibuja sobre el mapa.', null=True, verbose_name='Recorrido'),
        ),
    ]
