# Generated by Django 6.0.5 on 2026-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gym_allow_member_schedule_changes_and_more'),
        ('members', '0007_alter_member_photo'),
        ('plans', '0005_remove_membershipplan_active'),
        ('subscriptions', '0005_alter_subscription_end_date_alter_subscription_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['gym', 'end_date'], name='subscriptio_gym_id_c00fff_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['gym', 'paid'], name='subscriptio_gym_id_deb0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['gym', '-created_at'], name='subscriptio_gym_id_1d4157_idx'),
        ),
    ]
