# Generated by Django 6.0.5 on 2026-06-16 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_add_indexes'),
        ('gyms', '0007_gym_allow_member_schedule_changes_and_more'),
        ('members', '0007_alter_member_photo'),
        ('plans', '0006_add_description_weekly_visits_active'),
        ('subscriptions', '0008_planchangerequest_current_plan_name_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(help_text='Snapshot del nombre del horario (ej: Lunes 10:00)', max_length=50)),
                ('day', models.CharField(help_text='Snapshot del día del horario (ej: monday)', max_length=20)),
                ('hour', models.CharField(help_text='Snapshot de la hora del horario (ej: 10:00)', max_length=10)),
                ('activated', models.BooleanField(default=False, help_text='Indica si las agendas ya fueron activadas tras la ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Fecha en que el cambio de plan se hará efectivo. Calculada automáticamente al aprobar.', null=True),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('executed', 'Ejecutado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['status', 'effective_date'], name='subscriptio_status_a2fcbf_idx'),
        ),
        migrations.AddField(
            model_name='plannedschedule',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_schedules', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='plannedschedule',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_schedules', to='members.member'),
        ),
        migrations.AddField(
            model_name='plannedschedule',
            name='plan_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_schedules', to='subscriptions.planchangerequest'),
        ),
        migrations.AddField(
            model_name='plannedschedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_schedules', to='attendance.scheduleslot'),
        ),
        migrations.AddIndex(
            model_name='plannedschedule',
            index=models.Index(fields=['gym', 'activated'], name='subscriptio_gym_id_e3b54e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plannedschedule',
            unique_together={('member', 'slot', 'plan_change')},
        ),
    ]
