# Generated by Django 6.0.5 on 2026-06-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_plan_change_deferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Si la suscripción se renueva automáticamente al próximo mes'),
        ),
    ]
