# Generated by Django 6.0.5 on 2026-07-15 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_monthly_price'),
        ('attendance', '0017_alter_attendance_options_and_more'),
        ('gyms', '0013_gym_allow_activity_without_membership'),
        ('members', '0009_member_entry_mode'),
        ('plans', '0010_membershipplan_is_base'),
        ('subscriptions', '0013_harden_subscription_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planchangerequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Solicitud de cambio de plan', 'verbose_name_plural': 'Solicitudes de cambio de plan'},
        ),
        migrations.AlterModelOptions(
            name='plannedschedule',
            options={'verbose_name': 'Horario planificado', 'verbose_name_plural': 'Horarios planificados'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionitem',
            name='unique_active_item_per_subscription',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_auto_re_cb2d04_idx',
            old_name='subscriptio_auto_renew_end_date_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_member__cc8aa1_idx',
            old_name='subscriptio_member_start_date_idx',
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='activities.activity', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='item_type',
            field=models.CharField(choices=[('plan', 'Plan de membresía'), ('activity', 'Actividad')], default='plan', max_length=20, verbose_name='Tipo de item'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='name_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot del nombre del plan o actividad.', max_length=150, verbose_name='Nombre al momento de contratación'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas del administrador'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='current_plan_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del plan actual'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='current_schedules_snapshot',
            field=models.JSONField(verbose_name='Horarios actuales'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Fecha en que el cambio de plan se hará efectivo. Calculada automáticamente al aprobar.', null=True, verbose_name='Fecha de efecto'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='requested_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='plans.membershipplan', verbose_name='Plan solicitado'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('executed', 'Ejecutado'), ('rejected', 'Rechazado'), ('cancelled_by_member', 'Cancelado por el socio'), ('cancelled_by_staff', 'Cancelado por el staff')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='target_schedules_snapshot',
            field=models.JSONField(verbose_name='Horarios objetivo'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='activated',
            field=models.BooleanField(default=False, help_text='Indica si las agendas ya fueron activadas tras la ejecución', verbose_name='Activado'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='day',
            field=models.CharField(help_text='Snapshot del día del horario (ej: monday)', max_length=20, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_schedules', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='hour',
            field=models.CharField(help_text='Snapshot de la hora del horario (ej: 10:00)', max_length=10, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_schedules', to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='plan_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_schedules', to='subscriptions.planchangerequest', verbose_name='Cambio de plan'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_schedules', to='attendance.scheduleslot', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='plannedschedule',
            name='slot_name',
            field=models.CharField(help_text='Snapshot del nombre del horario (ej: Lunes 10:00)', max_length=50, verbose_name='Nombre del horario'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Si la suscripción se renueva automáticamente al próximo mes', verbose_name='Renovación automática'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.membershipplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='plans.membershipplan', verbose_name='Plan'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('plan__isnull', False), ('status', 'active')), fields=('subscription', 'plan'), name='unique_active_plan_item_per_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('activity__isnull', False), ('status', 'active')), fields=('subscription', 'activity'), name='unique_active_activity_item_per_subscription'),
        ),
    ]
