# Generated by Django 6.0.5 on 2026-07-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_planchangerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planchangerequest',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_change_requests', to='subscriptions.subscription', verbose_name='Suscripción'),
        ),
    ]
