# Generated by Django 6.0.5 on 2026-08-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_add_origin_to_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='origin',
            field=models.CharField(choices=[('onboarding', 'Alta'), ('auto_renewal', 'Renovación automática'), ('plan_change', 'Cambio de plan'), ('recovery', 'Recuperación')], default='onboarding', help_text='Flujo que originó esta suscripción (auditoría).', max_length=20, verbose_name='Origen'),
        ),
    ]
