# Generated by Django 6.0.5 on 2026-09-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_alter_subscription_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nombre de la tarea')),
                ('last_run', models.DateTimeField(verbose_name='Última ejecución')),
                ('last_status', models.CharField(default='ok', help_text='ok / error / locked / not_due', max_length=20, verbose_name='Último estado')),
                ('last_duration_seconds', models.FloatField(default=0, verbose_name='Duración de la última ejecución')),
                ('last_result', models.JSONField(blank=True, null=True, verbose_name='Resultado de la última ejecución')),
                ('last_error', models.TextField(blank=True, verbose_name='Último error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Ejecución de tarea programada',
                'verbose_name_plural': 'Ejecuciones de tareas programadas',
            },
        ),
    ]
