# Generated by Django 6.0.5 on 2026-09-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_add_recovery_session_source'),
        ('personal_training', '0001_initial'),
        ('plans', '0011_alter_membershipplan_duration_days'),
        ('subscriptions', '0019_taskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='personal_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='personal_training.personaltrainingservice', verbose_name='Entrenamiento personal'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='item_type',
            field=models.CharField(choices=[('plan', 'Plan de membresía'), ('activity', 'Actividad'), ('personal_training', 'Entrenamiento personal')], default='plan', max_length=20, verbose_name='Tipo de item'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('personal_training__isnull', False), ('status', 'active')), fields=('subscription', 'personal_training'), name='unique_active_pt_item_per_subscription'),
        ),
    ]
