# Generated by Django 6.0.5 on 2026-09-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_enrollment_no_show_scan_until_and_more'),
        ('outings', '0001_initial'),
        ('personal_training', '0002_personaltrainingassignment_no_show_scan_until_and_more'),
        ('plans', '0011_alter_membershipplan_duration_days'),
        ('subscriptions', '0020_subscriptionitem_personal_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='outing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='outings.outing', verbose_name='Salida grupal'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='item_type',
            field=models.CharField(choices=[('plan', 'Plan de membresía'), ('activity', 'Actividad'), ('personal_training', 'Entrenamiento personal'), ('outing', 'Salida grupal')], default='plan', max_length=20, verbose_name='Tipo de item'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('outing__isnull', False), ('status', 'active')), fields=('subscription', 'outing'), name='unique_active_outing_item_per_subscription'),
        ),
    ]
