# Generated by Django 6.0.8 on 2026-09-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_subscriptionitem_outing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_percent_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de descuento del día en que se emitió la suscripción. Un descuento desactivado después no altera este período ya facturado; None significa fila legacy (se usa el descuento vivo).', null=True, verbose_name='Descuento congelado'),
        ),
    ]
