# Generated by Django 6.0.8 on 2026-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_subscription_discount_percent_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='prorated',
            field=models.BooleanField(default=False, help_text='Alta posterior al día de vencimiento del gimnasio: el primer período se facturó solo por los días restantes del mes. Se decide una sola vez al abrir la suscripción; sin backfill, las filas anteriores a esta regla quedan en False (se facturaron completas).', verbose_name='Primer mes prorrateado'),
        ),
    ]
