# Generated by Django 6.0.5 on 2026-06-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0010_feature_flags_v1'),
        ('members', '0008_alter_member_options_alter_member_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gyms.gym', verbose_name='Gimnasio')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'unique_together': {('gym', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado')], max_length=20, verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='activities.activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Horario de actividad',
                'verbose_name_plural': 'Horarios de actividades',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscripto')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_enrollments', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_enrollments', to='members.member', verbose_name='Miembro')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='activities.activityschedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.AddConstraint(
            model_name='activityschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='activityschedule_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='activityschedule',
            unique_together={('activity', 'day', 'start_time')},
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('gym', 'member', 'schedule'), name='unique_active_enrollment'),
        ),
    ]
