# Generated by Django 6.0.5 on 2026-06-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_service'),
        ('plans', '0009_alter_membershipplan_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('service', 'name')},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='gym',
        ),
    ]
