# Generated by Django 6.0.5 on 2026-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_unique_together_remove_activity_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
