# Generated by Django 6.0.5 on 2026-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_add_active_to_activityschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo mensual de la actividad. Se factura como SubscriptionItem.', max_digits=10, verbose_name='Precio mensual'),
        ),
    ]
