# Generated by Django 6.0.5 on 2026-07-20 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_monthly_price'),
        ('subscriptions', '0016_backfill_plan_change_request_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='subscription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='subscriptions.subscriptionitem', verbose_name='Item de suscripción'),
        ),
    ]
