# Generated by Django 6.0.5 on 2026-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_backfill_enrollment_subscription_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='Nombre del profesor o profesora de la actividad.', max_length=100, verbose_name='Profesor/a'),
        ),
    ]
