# Generated by Django 6.0.5 on 2026-09-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_activityschedule_day'),
        ('gyms', '0021_gymcloseddate'),
        ('members', '0010_member_affiliate_number_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='billing_mode',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('sessions', 'Por sesiones')], default='monthly', help_text='Mensual: cuota mensual fija. Por sesiones: el staff inscribe a cada socio en modalidad mensual o en un paquete de N sesiones.', max_length=20, verbose_name='Modalidad de cobro'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='modality',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('package', 'Paquete de sesiones')], default='monthly', help_text='Mensual: se factura la cuota de la actividad. Paquete: el socio asiste a un número fijo de sesiones.', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='package_total_sessions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de sesiones del paquete'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sellado_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto opcional de sellado o coseguro que cobra el gimnasio.', max_digits=10, null=True, verbose_name='Sellado / coseguro'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sellado_paid',
            field=models.BooleanField(default=False, verbose_name='Sellado cobrado'),
        ),
        migrations.CreateModel(
            name='ActivitySessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha de la sesión')),
                ('source', models.CharField(choices=[('auto', 'Automática'), ('manual', 'Manual')], default='manual', help_text='Automática (check-in) o manual (staff).', max_length=20, verbose_name='Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='activities.enrollment', verbose_name='Inscripción')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_session_records', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_session_records', to='members.member', verbose_name='Miembro')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_records', to='activities.activityschedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Sesión asistida',
                'verbose_name_plural': 'Sesiones asistidas',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'date', 'schedule'), name='unique_session_record')],
            },
        ),
    ]
