# Generated by Django 6.0.5 on 2026-09-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_activity_billing_mode_enrollment_modality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuánto pagó el socio de este paquete de sesiones.', max_digits=10, verbose_name='Monto cobrado'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por sesión para este socio. Define el monto que paga por cada sesión según su obra social.', max_digits=10, null=True, verbose_name='Precio por sesión'),
        ),
    ]
