# Generated by Django 6.0.5 on 2026-09-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_enrollment_amount_paid_enrollment_session_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysessionrecord',
            name='source',
            field=models.CharField(choices=[('auto', 'Automática'), ('manual', 'Manual'), ('recovery', 'Recuperación')], default='manual', help_text='Automática (check-in) o manual (staff).', max_length=20, verbose_name='Origen'),
        ),
    ]
