# Generated by Django 6.0.5 on 2026-06-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('plans', '0003_membershipplan_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='gym',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='plans',
                to='gyms.gym',
            ),
        ),
    ]