# Generated by Django 6.0.5 on 2026-06-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_membershipplan_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='active',
        ),
    ]
