# Generated by Django 6.0.5 on 2026-06-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gym_allow_member_schedule_changes_and_more'),
        ('plans', '0005_remove_membershipplan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='weekly_visits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='membershipplan',
            unique_together={('gym', 'name')},
        ),
    ]
