# Generated by Django 6.0.5 on 2026-06-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_feature_flags_v1'),
        ('plans', '0006_add_description_weekly_visits_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.IntegerField(verbose_name='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del plan'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='weekly_visits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Visitas semanales'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gyms.gym', verbose_name='Gimnasio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'unique_together': {('gym', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plans.service', verbose_name='Servicio'),
        ),
    ]
