# Generated by Django 6.0.5 on 2026-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_membershipplan_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='is_base',
            field=models.BooleanField(default=False, help_text='Plan interno para acceso sin membresía. No se muestra en listados.', verbose_name='Plan base'),
        ),
    ]
