# Generated by Django 6.0.5 on 2026-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_membershipplan_is_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.IntegerField(help_text='Valor informativo/display. La facturación es mensual por período calendario e ignora este campo para calcular fechas.', verbose_name='Duración (días)'),
        ),
    ]
