# Generated by Django 6.0.5 on 2026-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0002_alter_member_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendanceschedule',
            name='hour',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendanceschedule',
            unique_together={('member', 'day', 'hour')},
        ),
    ]
