# Generated by Django 6.0.5 on 2026-05-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('schedule', 'date')},
        ),
    ]
