# Generated by Django 6.0.5 on 2026-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceschedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
