# Generated by Django 6.0.5 on 2026-06-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendanceschedule_active'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='attendanceschedule',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_schedules', to='gyms.gym'),
        ),
    ]
