# Generated by Django 6.0.5 on 2026-06-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_gym_attendanceschedule_gym'),
        ('gyms', '0001_initial'),
        ('members', '0003_member_gym'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceschedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.attendanceschedule'),
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_schedules', to='gyms.gym'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('gym', 'schedule', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceschedule',
            unique_together={('gym', 'member', 'day', 'hour')},
        ),
    ]
