# Generated by Django 6.0.5 on 2026-06-09 17:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_slots(apps, schema_editor):
    AttendanceSchedule = apps.get_model("attendance", "AttendanceSchedule")
    ScheduleSlot = apps.get_model("attendance", "ScheduleSlot")

    seen = set()

    for schedule in AttendanceSchedule.objects.all().iterator():
        key = (schedule.gym_id, schedule.day, schedule.hour)

        if key not in seen:
            seen.add(key)

            slot, _ = ScheduleSlot.objects.get_or_create(
                gym_id=schedule.gym_id,
                day=schedule.day,
                hour=schedule.hour,
            )

            schedule.slot = slot
            schedule.save(update_fields=["slot"])
        else:
            slot = ScheduleSlot.objects.get(
                gym_id=schedule.gym_id,
                day=schedule.day,
                hour=schedule.hour,
            )

            schedule.slot = slot
            schedule.save(update_fields=["slot"])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_unique_together_and_more'),
        ('gyms', '0006_gym_email_gym_phone_gym_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado')], max_length=20)),
                ('hour', models.TimeField()),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='gyms.gym')),
            ],
            options={
                'unique_together': {('gym', 'day', 'hour')},
            },
        ),
        migrations.AddField(
            model_name='attendanceschedule',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_schedules', to='attendance.scheduleslot'),
        ),
        migrations.RunPython(backfill_slots, reverse_code=migrations.RunPython.noop),
    ]
