# Generated by Django 6.0.5 on 2026-06-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_scheduleslot_attendanceschedule_slot'),
        ('gyms', '0006_gym_email_gym_phone_gym_whatsapp'),
        ('members', '0007_alter_member_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceschedule',
            unique_together={('gym', 'member', 'slot')},
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='attendance.scheduleslot'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='attendanceschedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='attendanceschedule',
            name='hour',
        ),
    ]
