# Generated by Django 6.0.5 on 2026-06-09 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_phase2b'),
        ('gyms', '0007_gym_allow_member_schedule_changes_and_more'),
        ('members', '0007_alter_member_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('current_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_from', to='attendance.attendanceschedule')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to='gyms.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to='members.member')),
                ('requested_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_to', to='attendance.scheduleslot')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['gym', 'status'], name='attendance__gym_id_e3ea87_idx'), models.Index(fields=['member', 'status'], name='attendance__member__e1aa98_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('member', 'current_schedule'), name='unique_pending_change_request')],
            },
        ),
    ]
