# Generated by Django 6.0.5 on 2026-06-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendance_swap_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.scheduleslot'),
        ),
    ]
