# Generated by Django 6.0.5 on 2026-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_backfill_attendance_slot'),
        ('gyms', '0007_gym_allow_member_schedule_changes_and_more'),
        ('members', '0007_alter_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['gym', 'date'], name='attendance__gym_id_6c516f_idx'),
        ),
    ]
