# Generated by Django 6.0.5 on 2026-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('executed', 'Ejecutado'), ('rejected', 'Rechazado'), ('cancelled_by_member', 'Cancelado por el socio'), ('cancelled_by_staff', 'Cancelado por el staff')], default='pending', max_length=20),
        ),
    ]
