# Generated by Django 6.0.5 on 2026-07-15 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_phase8a_request_statuses'),
        ('gyms', '0013_gym_allow_activity_without_membership'),
        ('members', '0009_member_entry_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='attendanceschedule',
            options={'verbose_name': 'Agenda de asistencia', 'verbose_name_plural': 'Agendas de asistencia'},
        ),
        migrations.AlterModelOptions(
            name='schedulechangerequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Solicitud de cambio de horario', 'verbose_name_plural': 'Solicitudes de cambio de horario'},
        ),
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'verbose_name': 'Horario disponible', 'verbose_name_plural': 'Horarios disponibles'},
        ),
        migrations.AlterModelOptions(
            name='scheduleswaprequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Solicitud de intercambio', 'verbose_name_plural': 'Solicitudes de intercambio'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.attendanceschedule', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.scheduleslot', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='swap_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.scheduleswaprequest', verbose_name='Solicitud de intercambio'),
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_schedules', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='attendance.scheduleslot', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas del administrador'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='current_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_from', to='attendance.attendanceschedule', verbose_name='Agenda actual'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='requested_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_to', to='attendance.scheduleslot', verbose_name='Horario solicitado'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('executed', 'Ejecutado'), ('rejected', 'Rechazado'), ('cancelled_by_member', 'Cancelado por el socio'), ('cancelled_by_staff', 'Cancelado por el staff')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado')], max_length=20, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='hour',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas del administrador'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='destination_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_requests_to', to='attendance.scheduleslot', verbose_name='Horario de destino'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_swap_requests', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_swap_requests', to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='origin_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_requests_from', to='attendance.attendanceschedule', verbose_name='Agenda de origen'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='scheduleswaprequest',
            name='swap_date',
            field=models.DateField(verbose_name='Fecha de intercambio'),
        ),
    ]
