# Generated by Django 6.0.5 on 2026-07-20 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_attendance_options_and_more'),
        ('subscriptions', '0016_backfill_plan_change_request_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceschedule',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='subscriptions.subscription', verbose_name='Suscripción'),
        ),
    ]
