# Generated by Django 6.0.5 on 2026-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_backfill_attendance_schedule_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleslot',
            name='day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=20, verbose_name='Día'),
        ),
    ]
