# Generated by Django 6.0.5 on 2026-09-10 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_enrollment_amount_paid_enrollment_session_price'),
        ('attendance', '0020_alter_scheduleslot_day'),
        ('gyms', '0023_gym_session_recovery_config'),
        ('members', '0014_member_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_recovery',
            field=models.BooleanField(default=False, verbose_name='Es recuperación'),
        ),
        migrations.CreateModel(
            name='SessionRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('training', 'Entrenamiento gimnasio'), ('activity', 'Clase de actividad')], default='training', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('used', 'Usada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='available', max_length=20, verbose_name='Estado')),
                ('expires_at', models.DateField(verbose_name='Expira el')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usada el')),
                ('used_date', models.DateField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_recoveries', to='activities.activity', verbose_name='Actividad')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_session_recoveries', to=settings.AUTH_USER_MODEL, verbose_name='Otorgada por')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_recoveries', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_recoveries', to='members.member', verbose_name='Miembro')),
                ('used_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoveries_used', to='activities.activityschedule', verbose_name='Clase usada')),
                ('used_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoveries_used', to='attendance.scheduleslot', verbose_name='Horario usado')),
            ],
            options={
                'verbose_name': 'Recuperación de clase',
                'verbose_name_plural': 'Recuperaciones de clases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='recovery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.sessionrecovery', verbose_name='Recuperación'),
        ),
        migrations.AddIndex(
            model_name='sessionrecovery',
            index=models.Index(fields=['member', 'status'], name='attendance__member__6385d8_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecovery',
            index=models.Index(fields=['gym', 'status'], name='attendance__gym_id_eef9f2_idx'),
        ),
    ]
