# Generated by Django 6.0.5 on 2026-09-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrecovery',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('available', 'Disponible'), ('used', 'Usada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='available', max_length=20, verbose_name='Estado'),
        ),
    ]
