# Generated by Django 6.0.5 on 2026-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_member_remove_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
