# Generated by Django 6.0.5 on 2026-06-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_notes_payment_payment_method'),
        ('subscriptions', '0005_alter_subscription_end_date_alter_subscription_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='member_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription'),
        ),
    ]
