# Generated by Django 6.0.5 on 2026-06-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_member_name_payment_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
