# Generated by Django 6.0.5 on 2026-06-11 16:20

import django.db.models.deletion
from django.db import migrations, models


def backfill_member(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    qs = Payment.objects.filter(
        subscription__isnull=False, member__isnull=True
    )
    for payment in qs.iterator():
        payment_id = payment.subscription.member_id
        if payment_id:
            Payment.objects.filter(pk=payment.pk).update(member_id=payment_id)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_photo'),
        ('payments', '0007_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.member'),
        ),
        migrations.RunPython(backfill_member, migrations.RunPython.noop),
    ]
