# Generated by Django 6.0.5 on 2026-09-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_enrollment_amount_paid_enrollment_session_price'),
        ('payments', '0009_alter_payment_options_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='concept',
            field=models.CharField(choices=[('subscription', 'Suscripción'), ('sellado', 'Sellado'), ('coseguro', 'Coseguro por sesiones')], default='subscription', max_length=20, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='activities.enrollment', verbose_name='Inscripción'),
        ),
    ]
