# Generated by Django 6.0.5 on 2026-09-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_concept_payment_enrollment'),
        ('personal_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='personal_training_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='personal_training.personaltrainingassignment', verbose_name='Asignación de entrenamiento personal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='concept',
            field=models.CharField(choices=[('subscription', 'Suscripción'), ('sellado', 'Sellado'), ('coseguro', 'Coseguro por sesiones'), ('personal_training', 'Entrenamiento personal')], default='subscription', max_length=20, verbose_name='Concepto'),
        ),
    ]
