# Generated by Django 6.0.5 on 2026-09-22 17:33

import django.db.models.deletion
from django.db import migrations, models


def backfill_outing_package_payments(apps, schema_editor):
    """Materialize a Payment for every already-collected outing package pay.

    Before this change, outing package co-pays were accumulated directly on
    OutingEnrollment.amount_paid with no Payment rows. Once amount_paid is
    synced from Payments, those collected amounts would otherwise resurface
    as outstanding debt.
    """
    Payment = apps.get_model("payments", "Payment")
    OutingEnrollment = apps.get_model("outings", "OutingEnrollment")

    qs = OutingEnrollment.objects.filter(
        active=True,
        modality="package",
        amount_paid__gt=0,
    ).select_related("member", "schedule__outing")

    for enrollment in qs.iterator():
        if Payment.objects.filter(
            outing_enrollment_id=enrollment.pk
        ).exists():
            continue
        Payment.objects.create(
            gym_id=enrollment.gym_id,
            member=enrollment.member,
            outing_enrollment=enrollment,
            concept="outing",
            amount=enrollment.amount_paid,
            payment_method="cash",
            notes="Backfill de pago de paquete de salidas",
            member_name=(
                f"{enrollment.member.first_name} "
                f"{enrollment.member.last_name}"
            ),
            plan_name=f"{enrollment.schedule.outing.name} · Sesiones",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0002_outingenrollmentrequest'),
        ('payments', '0011_payment_personal_training_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='outing_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='outings.outingenrollment', verbose_name='Inscripción a salida'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='concept',
            field=models.CharField(choices=[('subscription', 'Suscripción'), ('sellado', 'Sellado'), ('coseguro', 'Coseguro por sesiones'), ('personal_training', 'Entrenamiento personal'), ('outing', 'Salida por sesiones')], default='subscription', max_length=20, verbose_name='Concepto'),
        ),
        migrations.RunPython(
            backfill_outing_package_payments,
            migrations.RunPython.noop,
        ),
    ]
