# Generated by Django 6.0.8 on 2026-09-30 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_outing_enrollment_alter_payment_concept'),
        ('subscriptions', '0022_subscription_discount_percent_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='applied_to',
            field=models.ForeignKey(blank=True, help_text='Suscripción en la que este saldo a favor fue consumido. Nulo significa saldo a favor abierto (no consumido todavía).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.subscription', verbose_name='Consumido en suscripción'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='concept',
            field=models.CharField(choices=[('subscription', 'Suscripción'), ('sellado', 'Sellado'), ('coseguro', 'Coseguro por sesiones'), ('personal_training', 'Entrenamiento personal'), ('outing', 'Salida por sesiones'), ('credit', 'Saldo a favor')], default='subscription', max_length=20, verbose_name='Concepto'),
        ),
    ]
