# Generated by Django 6.0.5 on 2026-06-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('members', '0003_member_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gyms.gym'),
        ),
    ]
