# Generated by Django 6.0.5 on 2026-06-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
