# Generated by Django 6.0.5 on 2026-06-22 20:36

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_alter_gym_options_alter_gym_access_block_day_and_more'),
        ('members', '0007_alter_member_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
        migrations.AlterField(
            model_name='member',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de acceso'),
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto'),
        ),
    ]
