# Generated by Django 6.0.5 on 2026-09-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_entry_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='affiliate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº de afiliado'),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='member',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nº de documento'),
        ),
        migrations.AddField(
            model_name='member',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=120, verbose_name='Obra social / seguro médico'),
        ),
    ]
