# Generated by Django 6.0.5 on 2026-09-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0021_gymcloseddate'),
        ('members', '0010_member_affiliate_number_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Obra social / seguro médico')),
                ('session_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio que paga el socio por cada sesión de actividades por sesiones (ej. 10 sesiones de kinesiología).', max_digits=10, verbose_name='Precio por sesión')),
                ('active', models.BooleanField(default=True, help_text='Inactivar oculta la obra social en los selectores y desvincula a los socios al volver a cargar la ficha.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insurances', to='gyms.gym', verbose_name='Gimnasio')),
            ],
            options={
                'verbose_name': 'Obra social',
                'verbose_name_plural': 'Obras sociales',
                'ordering': ['name'],
                'unique_together': {('gym', 'name')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='insurance',
            field=models.ForeignKey(blank=True, help_text='Obra social configurada, define el precio por sesión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.healthinsurance', verbose_name='Obra social configurada'),
        ),
    ]
