# Generated by Django 6.0.5 on 2026-09-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_healthinsurance_sellado_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_comp',
            field=models.BooleanField(default=False, help_text='Socio con acceso de cortesía: no se le cobra por la membresía ni por las actividades y nunca se le bloquea por falta de pago.', verbose_name='Pase de cortesía'),
        ),
    ]
