# Generated by Django 6.0.5 on 2026-09-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0022_discount'),
        ('members', '0013_member_is_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Descuento porcentual asignado por el gimnasio a este socio. Se aplica sobre el total mensual (plan + actividades).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='gyms.discount', verbose_name='Descuento'),
        ),
    ]
