# Generated by Django 6.0.5 on 2026-09-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0024_remove_gym_session_recovery_expiration_days'),
        ('members', '0014_member_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medical_order', 'Orden médica / sesiones'), ('payment_proof', 'Comprobante de pago'), ('electro', 'Electrocardiograma / estudios'), ('other', 'Otro')], max_length=32, verbose_name='Categoría')),
                ('file', models.CharField(blank=True, max_length=255, verbose_name='Adjunto (public_id de Cloudinary)')),
                ('note', models.TextField(blank=True, help_text='Aclaración opcional del socio (ej. nombre del titular de la transferencia).', verbose_name='Nota')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Revisado por el staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gyms.gym', verbose_name='Gimnasio')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='members.member', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Adjunto del socio',
                'verbose_name_plural': 'Adjuntos de los socios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'reviewed'], name='members_mem_gym_id_b23cd7_idx'), models.Index(fields=['member', 'created_at'], name='members_mem_member__8e5a51_idx')],
            },
        ),
    ]
