# Generated by Django 6.0.5 on 2026-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_memberattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección del socio (ej: domicilio donde entrena el personal trainer).', max_length=255, verbose_name='Dirección'),
        ),
    ]
