# Generated by Django 6.0.5 on 2026-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='Whatsapp'),
        ),
    ]
