# Generated by Django 6.0.8 on 2026-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_member_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_token_previous',
            field=models.CharField(blank=True, help_text='Token de una generación anterior, aceptado brevemente para no romper URLs/links ya impresos cuando el portal rota el token.', max_length=64, null=True, verbose_name='Token de acceso anterior'),
        ),
        migrations.AddField(
            model_name='member',
            name='access_token_issued_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de emisión del token de portal actual. Controla la rotación automática (P1-1): al leer los datos del socio, un token más viejo que MEMBER_ACCESS_TOKEN_TTL_DAYS se reemplaza por uno nuevo y se devuelve en la respuesta.', null=True, verbose_name='Token de acceso emitido el'),
        ),
    ]