# Generated by Django 6.0.5 on 2026-06-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0003_alter_gym_onboarding_code'),
        ('members', '0004_alter_member_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_templates', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='gyms.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='members.member')),
                ('routine_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routinetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(max_length=20)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.exercise')),
                ('routine_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.routinetemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
