# Generated by Django 6.0.5 on 2026-06-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.exercise')),
                ('routine_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='routines.routinetemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
