# Generated by Django 6.0.5 on 2026-06-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_routineexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutineTemplateExercise',
        ),
    ]
