# Generated by Django 6.0.5 on 2026-06-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_delete_routinetemplateexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('core', 'Core'), ('cardio', 'Cardio'), ('movilidad', 'Movilidad')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Fuerza'), ('bodyweight', 'Peso corporal'), ('cardio', 'Cardio')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
