# Generated by Django 6.0.5 on 2026-06-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_add_exercise_category_and_routine_exercise_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('routine_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='routines.routineassignment')),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routineexercise')),
            ],
            options={
                'unique_together': {('routine_assignment', 'routine_exercise', 'set_number')},
            },
        ),
    ]
