# Generated by Django 6.0.5 on 2026-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_workout_set_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='rest_mode',
            field=models.CharField(choices=[('between_sets', 'Entre series'), ('after_exercise', 'Al finalizar ejercicio'), ('none', 'Sin descanso')], default='between_sets', max_length=20),
        ),
    ]
