# Generated by Django 6.0.5 on 2026-06-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_add_rest_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='next_exercise_rest_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
