# Generated by Django 6.0.5 on 2026-06-22 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_workout_set_dates(apps, schema_editor):
    WorkoutSet = apps.get_model("routines", "WorkoutSet")
    today = django.utils.timezone.localdate()
    for ws in WorkoutSet.objects.iterator(chunk_size=500):
        ws.date = ws.completed_at.date() if ws.completed_at else today
        ws.save(update_fields=["date"])


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_alter_gym_options_alter_gym_access_block_day_and_more'),
        ('members', '0008_alter_member_options_alter_member_access_token_and_more'),
        ('routines', '0007_add_next_exercise_rest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='routineassignment',
            options={'verbose_name': 'Asignación de rutina', 'verbose_name_plural': 'Asignaciones de rutina'},
        ),
        migrations.AlterModelOptions(
            name='routineexercise',
            options={'ordering': ['order'], 'verbose_name': 'Ejercicio de rutina', 'verbose_name_plural': 'Ejercicios de rutina'},
        ),
        migrations.AlterModelOptions(
            name='routinetemplate',
            options={'verbose_name': 'Plantilla de rutina', 'verbose_name_plural': 'Plantillas de rutina'},
        ),
        migrations.AlterModelOptions(
            name='workoutset',
            options={'verbose_name': 'Serie de entrenamiento', 'verbose_name_plural': 'Series de entrenamiento'},
        ),
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.RunPython(
            code=backfill_workout_set_dates,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together={('routine_assignment', 'routine_exercise', 'set_number', 'date')},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('core', 'Core'), ('cardio', 'Cardio'), ('movilidad', 'Movilidad')], max_length=20, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='routineassignment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='routineassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='routineassignment',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='routineassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='members.member', verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='routineassignment',
            name='routine_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routinetemplate', verbose_name='Plantilla de rutina'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Fuerza'), ('bodyweight', 'Peso corporal'), ('cardio', 'Cardio')], default='strength', max_length=20, verbose_name='Tipo de ejercicio'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='next_exercise_rest_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Descanso antes del próximo (segundos)'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='reps',
            field=models.CharField(blank=True, max_length=50, verbose_name='Repeticiones'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='rest_mode',
            field=models.CharField(choices=[('between_sets', 'Entre series'), ('after_exercise', 'Al finalizar ejercicio'), ('none', 'Sin descanso')], default='between_sets', max_length=20, verbose_name='Modo de descanso'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='Descanso (segundos)'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='routine_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='routines.routinetemplate', verbose_name='Plantilla de rutina'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='sets',
            field=models.PositiveIntegerField(default=3, verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='routinetemplate',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_templates', to='gyms.gym', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='routinetemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la rutina'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='routine_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='routines.routineassignment', verbose_name='Asignación de rutina'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='routine_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routineexercise', verbose_name='Ejercicio de rutina'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='set_number',
            field=models.PositiveIntegerField(verbose_name='Número de serie'),
        ),
    ]
