# Generated by Django 6.0.5 on 2026-09-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0029_feature_whitelist_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del local')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='Categoría / tipo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Contacto (teléfono / WhatsApp)')),
                ('discount', models.CharField(help_text='Texto libre, ej: 10% de descuento, 2x1, $500.', max_length=120, verbose_name='Descuento / beneficio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / condiciones')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_businesses', to='gyms.gym', verbose_name='Gimnasio')),
            ],
            options={
                'verbose_name': 'Local adherido',
                'verbose_name_plural': 'Locales adheridos',
                'ordering': ['gym', 'name'],
            },
        ),
    ]
