# Generated by Django 6.0.5 on 2026-08-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_options_alter_userprofile_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño'), ('staff', 'Staff')], default='staff', max_length=10, verbose_name='Rol'),
        ),
    ]
