# Generated by Django 6.0.5 on 2026-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_backfill_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño'), ('staff', 'Staff'), ('professor', 'Profesor')], default='staff', max_length=12, verbose_name='Rol'),
        ),
    ]
