# Generated by Django 6.0.5 on 2026-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_add_professor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Varón'), ('female', 'Mujer')], help_text='Género del/la entrenador/a, usado para filtrar trainers compatibles.', max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño'), ('staff', 'Staff'), ('professor', 'Profesor'), ('trainer', 'Entrenador/a')], default='staff', max_length=12, verbose_name='Rol'),
        ),
    ]
