# Generated by Django 6.0.5 on 2026-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='onboarding_code',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
