# Generated by Django 6.0.5 on 2026-06-03 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_onboarding_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='onboarding_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
