# Generated by Django 6.0.5 on 2026-06-07 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_gym_onboarding_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
