# Generated by Django 6.0.5 on 2026-06-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gym_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='default_schedule_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
