# Generated by Django 6.0.5 on 2026-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gym_default_schedule_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gym',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
