# Generated by Django 6.0.5 on 2026-06-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_gym_email_gym_phone_gym_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allow_member_schedule_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='schedule_change_notice_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
