# Generated by Django 6.0.5 on 2026-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gym_allow_member_schedule_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='access_block_day',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='gym',
            name='allow_plan_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='allow_schedule_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='max_schedule_changes_per_month',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='gym',
            name='payment_due_day',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='schedule_change_cooldown_hours',
            field=models.PositiveIntegerField(default=168),
        ),
        migrations.AddField(
            model_name='gym',
            name='schedule_change_notice_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
