# Generated by Django 6.0.5 on 2026-06-22 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_phase8a_gym_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': 'Gimnasio', 'verbose_name_plural': 'Gimnasios'},
        ),
        migrations.AlterField(
            model_name='gym',
            name='access_block_day',
            field=models.PositiveIntegerField(default=16, verbose_name='Día de bloqueo'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='allow_member_schedule_changes',
            field=models.BooleanField(default=False, verbose_name='Permitir cambios de horario'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='allow_plan_changes',
            field=models.BooleanField(default=True, verbose_name='Permitir cambios de plan'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='allow_schedule_changes',
            field=models.BooleanField(default=True, verbose_name='Permitir cambios de horario'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='default_schedule_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad por defecto'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='max_schedule_changes_per_month',
            field=models.PositiveIntegerField(default=4, verbose_name='Máximo de cambios por mes'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='onboarding_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de registro'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='payment_due_day',
            field=models.PositiveIntegerField(default=10, verbose_name='Día de vencimiento'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='schedule_change_cooldown_hours',
            field=models.PositiveIntegerField(default=168, verbose_name='Horas de espera entre cambios'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='schedule_change_notice_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de aviso para cambios'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='schedule_change_notice_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Horas de aviso para cambios'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp'),
        ),
    ]
