# Generated by Django 6.0.5 on 2026-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_alter_gym_options_alter_gym_access_block_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Características'),
        ),
    ]
