# Generated by Django 6.0.5 on 2026-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_migrate_extras_to_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allow_activity_without_membership',
            field=models.BooleanField(default=False, help_text='Si está activo, los socios pueden inscribirse en actividades sin comprar una membresía de gimnasio.', verbose_name='Permitir actividades sin membresía'),
        ),
    ]
