# Generated by Django 6.0.5 on 2026-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0014_enable_activity_without_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='allow_activity_without_membership',
            field=models.BooleanField(default=True, help_text='Control de plataforma: cuando está activo, los socios con plan base (solo actividades, sin membresía de gimnasio) se renuevan automáticamente en cada ciclo. Se oculta al staff del gimnasio y se gestiona desde el admin central.', verbose_name='Renovar socios solo-actividad'),
        ),
    ]
