# Generated by Django 6.0.5 on 2026-08-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0015_alter_gym_allow_activity_without_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='schedule_change_notice_days',
        ),
    ]
