# Generated by Django 6.0.5 on 2026-08-28 15:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0016_remove_gym_schedule_change_notice_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='app_icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='app_icon'),
        ),
    ]
