# Generated by Django 6.0.5 on 2026-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0017_gym_app_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='qr_attendance_message',
            field=models.CharField(blank=True, default='Marcá tu asistencia escaneando este código', max_length=120, verbose_name='Mensaje del QR de asistencia'),
        ),
        migrations.AddField(
            model_name='gym',
            name='qr_registration_message',
            field=models.CharField(blank=True, default='Registrate como socio escaneando este código', max_length=120, verbose_name='Mensaje del QR de registro'),
        ),
    ]
