# Generated by Django 6.0.5 on 2026-08-31 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0018_gym_qr_attendance_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='access_block_day',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de bloqueo'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='payment_due_day',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de vencimiento'),
        ),
    ]
