# Generated by Django 6.0.5 on 2026-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0019_alter_gym_access_block_day_alter_gym_payment_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='seo_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='gym',
            name='seo_city',
            field=models.CharField(blank=True, help_text='Ciudad del gimnasio para aparecer en búsquedas locales.', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='gym',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Descripción breve (150-160 caracteres) que aparece en Google.', verbose_name='Descripción SEO'),
        ),
        migrations.AddField(
            model_name='gym',
            name='seo_hours',
            field=models.TextField(blank=True, help_text='Horarios de atención (ej: Lun a Vie 8-22, Sáb 9-14)', verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='gym',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Separadas por coma (ej: gimnasio, musculación, crossfit, rosario)', max_length=250, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='gym',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Título que aparece en Google (ej: Gimnasio Atlas | Musculación y CrossFit en Rosario)', max_length=120, verbose_name='Título SEO'),
        ),
    ]
