# Generated by Django 6.0.5 on 2026-09-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0020_gym_seo_address_gym_seo_city_gym_seo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_dates', to='gyms.gym', verbose_name='Gimnasio')),
            ],
            options={
                'verbose_name': 'Fecha cerrada',
                'verbose_name_plural': 'Fechas cerradas',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('gym', 'date'), name='unique_gym_closed_date')],
            },
        ),
    ]
