# Generated by Django 6.0.5 on 2026-09-09 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0021_gymcloseddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('discount_percent', models.PositiveSmallIntegerField(help_text='Porcentaje de descuento sobre lo que paga el socio (1 a 100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('active', models.BooleanField(default=True, help_text='Inactivar desvincula el descuento de los socios asignados: pasaron a pagar el precio completo.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='gyms.gym', verbose_name='Gimnasio')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-active', 'name'],
            },
        ),
    ]
