# Generated by Django 6.0.5 on 2026-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0026_feature_whitelist_personal_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='auto_deduct_missed_sessions',
            field=models.BooleanField(default=False, help_text='La tarea programada descuenta 1 sesión de los paquetes de clase o de entrenamiento personal cuando la persona no asiste a la fecha de su clase, a partir del día siguiente. Si el staff otorga una recuperación por esa falta, el descuento se anula.', verbose_name='Descontar sesiones no asistidas'),
        ),
    ]
