# Generated by Django 6.0.5 on 2026-09-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0027_gym_auto_deduct_missed_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='auto_deduct_missed_sessions',
        ),
    ]
