# Generated by Django 6.0.8 on 2026-09-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0030_feature_whitelist_outings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactivar desvincula el descuento de los socios asignados: pasaron a pagar el precio completo. No altera los períodos que ya se emitieron con este descuento: cada suscripción guarda el porcentaje con el que se facturó.', verbose_name='Activo'),
        ),
    ]
